on:
  workflow_call:

jobs:
  frontend-tests:
    name: Frontend Testes QA-Engineering-Lab
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/leohspaixao/qa-runner-js:latest
    timeout-minutes: 10
    env:
      TURBO_TELEMETRY_DISABLED: 1

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Pegar o caminho do cache do Yarn
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cachear o Yarn
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Instalar dependências do Monorepo
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Executar testes do Frontend
        working-directory: apps/frontend
        run: yarn test

      - name: Upload raw results (Vitest)
        uses: actions/upload-artifact@v4.4.0
        with:
          name: vitest
          path: qa-results/raw/vitest