on:
  workflow_call:

jobs:
  rest-assured-tests:
    name: RestAssured Testes QA-Engineering-Lab
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/leohspaixao/qa-runner-java:latest

    timeout-minutes: 10

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: qa_engineering_lab_database
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Pegar o caminho do cache do Yarn
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cachear o Yarn
        uses: actions/cache@v4
        working-directory: ${{ github.workspace }}
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Instalar dependÃªncias do monorepo
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Executar seeders
        run: chmod +x .github/scripts/run-seeders.sh && .github/scripts/run-seeders.sh
        env:
          DATABASE_URL: postgresql://postgres:postgres@postgres:5432/qa_engineering_lab_database?schema=public
          JWT_SECRET: jwt_secret

      - name: Subir backend
        working-directory: apps/backend
        run: |
          yarn build
          nohup node dist/src/main.js > /tmp/backend.log 2>&1 &
          npx wait-on http://localhost:3001/healthy -t 30000
          curl -v http://localhost:3001/healthy
        env:
          DATABASE_URL: postgresql://postgres:postgres@postgres:5432/qa_engineering_lab_database?schema=public
          JWT_SECRET: jwt_secret
          PORT: 3001

      - name: Executar testes
        working-directory: tests/restAssured
        run: make test
        env:
          REST_ASSURED_BASE_URL: http://localhost:3001

      - name: Salvar resultados
        uses: actions/upload-artifact@v4.4.0
        with:
          name: rest-assured
          path: qa-results/raw/rest-assured